"""Function symbol table: what Tabula simulates, and what Excel knows.

SUPPORTED   functions the evaluator implements (arity + which parameters
            accept ranges).  Single source of truth for the checker and the
            evaluator.
EXCEL_FUNCTIONS  names of real Excel functions.  A call to one of these that
            is not SUPPORTED is legal but unsimulated (its value is taken from
            Excel's cache and marked unverified); a call to anything else is an
            unknown function, the classic hallucination.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class FunctionSpec:
    name: str
    min_args: int
    max_args: int | None          # None = variadic
    range_params: frozenset | str  # 'all' or a set of 0-based argument indexes

    def accepts_range(self, index: int) -> bool:
        return self.range_params == "all" or index in self.range_params


def _spec(name, lo, hi, ranges=frozenset()):
    return FunctionSpec(name, lo, hi, ranges if ranges == "all" else frozenset(ranges))


SUPPORTED: dict[str, FunctionSpec] = {s.name: s for s in [
    _spec("SUM", 1, None, "all"),
    _spec("AVERAGE", 1, None, "all"),
    _spec("MIN", 1, None, "all"),
    _spec("MAX", 1, None, "all"),
    _spec("COUNT", 1, None, "all"),
    _spec("COUNTA", 1, None, "all"),
    _spec("COUNTIF", 2, 2, {0}),
    _spec("SUMIF", 2, 3, {0, 2}),
    _spec("ROUND", 2, 2),
    _spec("ABS", 1, 1),
    _spec("SQRT", 1, 1),
    _spec("MOD", 2, 2),
    _spec("POWER", 2, 2),
    _spec("IF", 2, 3),
    _spec("IFERROR", 2, 2),
    _spec("AND", 1, None, "all"),
    _spec("OR", 1, None, "all"),
    _spec("NOT", 1, 1),
    _spec("LEN", 1, 1),
    _spec("CONCAT", 1, None, "all"),
    _spec("CONCATENATE", 1, None),
    _spec("UPPER", 1, 1),
    _spec("LOWER", 1, 1),
    _spec("TRIM", 1, 1),
    _spec("ISNUMBER", 1, 1),
    _spec("ISBLANK", 1, 1),
    _spec("ISERROR", 1, 1),
]}

# Real Excel worksheet functions (Excel 365).  Used only for classification.
EXCEL_FUNCTIONS: frozenset[str] = frozenset("""
ABS ACCRINT ACCRINTM ACOS ACOSH ACOT ACOTH ADDRESS AGGREGATE AMORDEGRC AMORLINC AND ARABIC
AREAS ARRAYTOTEXT ASC ASIN ASINH ATAN ATAN2 ATANH AVEDEV AVERAGE AVERAGEA AVERAGEIF
AVERAGEIFS BAHTTEXT BASE BESSELI BESSELJ BESSELK BESSELY BETA.DIST BETA.INV BETADIST BETAINV
BIN2DEC BIN2HEX BIN2OCT BINOM.DIST BINOM.DIST.RANGE BINOM.INV BINOMDIST BITAND BITLSHIFT
BITOR BITRSHIFT BITXOR BYCOL BYROW CALL CEILING CEILING.MATH CEILING.PRECISE CELL CHAR
CHIDIST CHIINV CHISQ.DIST CHISQ.DIST.RT CHISQ.INV CHISQ.INV.RT CHISQ.TEST CHITEST CHOOSE
CHOOSECOLS CHOOSEROWS CLEAN CODE COLUMN COLUMNS COMBIN COMBINA COMPLEX CONCAT CONCATENATE
CONFIDENCE CONFIDENCE.NORM CONFIDENCE.T CONVERT CORREL COS COSH COT COTH COUNT COUNTA
COUNTBLANK COUNTIF COUNTIFS COUPDAYBS COUPDAYS COUPDAYSNC COUPNCD COUPNUM COUPPCD COVAR
COVARIANCE.P COVARIANCE.S CRITBINOM CSC CSCH CUBEKPIMEMBER CUBEMEMBER CUBEMEMBERPROPERTY
CUBERANKEDMEMBER CUBESET CUBESETCOUNT CUBEVALUE CUMIPMT CUMPRINC DATE DATEDIF DATEVALUE
DAVERAGE DAY DAYS DAYS360 DB DBCS DCOUNT DCOUNTA DDB DEC2BIN DEC2HEX DEC2OCT DECIMAL DEGREES
DELTA DEVSQ DGET DISC DMAX DMIN DOLLAR DOLLARDE DOLLARFR DPRODUCT DROP DSTDEV DSTDEVP DSUM
DURATION DVAR DVARP EDATE EFFECT ENCODEURL EOMONTH ERF ERF.PRECISE ERFC ERFC.PRECISE
ERROR.TYPE EUROCONVERT EVEN EXACT EXP EXPAND EXPON.DIST EXPONDIST F.DIST F.DIST.RT F.INV
F.INV.RT F.TEST FACT FACTDOUBLE FALSE FDIST FILTER FILTERXML FIND FINDB FINV FISHER
FISHERINV FIXED FLOOR FLOOR.MATH FLOOR.PRECISE FORECAST FORECAST.ETS FORECAST.ETS.CONFINT
FORECAST.ETS.SEASONALITY FORECAST.ETS.STAT FORECAST.LINEAR FORMULATEXT FREQUENCY FTEST FV
FVSCHEDULE GAMMA GAMMA.DIST GAMMA.INV GAMMADIST GAMMAINV GAMMALN GAMMALN.PRECISE GAUSS GCD
GEOMEAN GESTEP GETPIVOTDATA GROUPBY GROWTH HARMEAN HEX2BIN HEX2DEC HEX2OCT HLOOKUP HOUR
HSTACK HYPERLINK HYPGEOM.DIST HYPGEOMDIST IF IFERROR IFNA IFS IMABS IMAGE IMAGINARY
IMARGUMENT IMCONJUGATE IMCOS IMCOSH IMCOT IMCSC IMCSCH IMDIV IMEXP IMLN IMLOG10 IMLOG2
IMPOWER IMPRODUCT IMREAL IMSEC IMSECH IMSIN IMSINH IMSQRT IMSUB IMSUM IMTAN INDEX INDIRECT
INFO INT INTERCEPT INTRATE IPMT IRR ISBLANK ISERR ISERROR ISEVEN ISFORMULA ISLOGICAL ISNA
ISNONTEXT ISNUMBER ISO.CEILING ISODD ISOMITTED ISOWEEKNUM ISPMT ISREF ISTEXT KURT LAMBDA
LARGE LCM LEFT LEFTB LEN LENB LET LINEST LN LOG LOG10 LOGEST LOGINV LOGNORM.DIST
LOGNORM.INV LOGNORMDIST LOOKUP LOWER MAKEARRAY MAP MATCH MAX MAXA MAXIFS MDETERM MDURATION
MEDIAN MID MIDB MIN MINA MINIFS MINUTE MINVERSE MIRR MMULT MOD MODE MODE.MULT MODE.SNGL
MONTH MROUND MULTINOMIAL MUNIT N NA NEGBINOM.DIST NEGBINOMDIST NETWORKDAYS
NETWORKDAYS.INTL NOMINAL NORM.DIST NORM.INV NORM.S.DIST NORM.S.INV NORMDIST NORMINV
NORMSDIST NORMSINV NOT NOW NPER NPV NUMBERVALUE OCT2BIN OCT2DEC OCT2HEX ODD ODDFPRICE
ODDFYIELD ODDLPRICE ODDLYIELD OFFSET OR PDURATION PEARSON PERCENTILE PERCENTILE.EXC
PERCENTILE.INC PERCENTOF PERCENTRANK PERCENTRANK.EXC PERCENTRANK.INC PERMUT PERMUTATIONA
PHI PHONETIC PI PIVOTBY PMT POISSON POISSON.DIST POWER PPMT PRICE PRICEDISC PRICEMAT PROB
PRODUCT PROPER PV QUARTILE QUARTILE.EXC QUARTILE.INC QUOTIENT RADIANS RAND RANDARRAY
RANDBETWEEN RANK RANK.AVG RANK.EQ RATE RECEIVED REDUCE REGEXEXTRACT REGEXREPLACE REGEXTEST
REGISTER.ID REPLACE REPLACEB REPT RIGHT RIGHTB ROMAN ROUND ROUNDDOWN ROUNDUP ROW ROWS RRI
RSQ RTD SCAN SEARCH SEARCHB SEC SECH SECOND SEQUENCE SERIESSUM SHEET SHEETS SIGN SIN SINH
SKEW SKEW.P SLN SLOPE SMALL SORT SORTBY SQRT SQRTPI STANDARDIZE STDEV STDEV.P STDEV.S
STDEVA STDEVP STDEVPA STEYX SUBSTITUTE SUBTOTAL SUM SUMIF SUMIFS SUMPRODUCT SUMSQ SUMX2MY2
SUMX2PY2 SUMXMY2 SWITCH SYD T T.DIST T.DIST.2T T.DIST.RT T.INV T.INV.2T T.TEST TAKE TAN
TANH TBILLEQ TBILLPRICE TBILLYIELD TDIST TEXT TEXTAFTER TEXTBEFORE TEXTJOIN TEXTSPLIT TIME
TIMEVALUE TINV TOCOL TODAY TOROW TRANSLATE TRANSPOSE TREND TRIM TRIMMEAN TRIMRANGE TRUE
TRUNC TTEST TYPE UNICHAR UNICODE UNIQUE UPPER VALUE VALUETOTEXT VAR VAR.P VAR.S VARA VARP
VARPA VDB VLOOKUP VSTACK WEBSERVICE WEEKDAY WEEKNUM WEIBULL WEIBULL.DIST WORKDAY
WORKDAY.INTL WRAPCOLS WRAPROWS XIRR XLOOKUP XMATCH XNPV XOR YEAR YEARFRAC YIELD YIELDDISC
YIELDMAT Z.TEST ZTEST
""".split()) | frozenset(SUPPORTED)


def classify(name: str) -> str:
    """'supported' | 'unsimulated' | 'unknown' for an upper-cased function name."""
    if name in SUPPORTED:
        return "supported"
    if name in EXCEL_FUNCTIONS:
        return "unsimulated"
    return "unknown"


def uses_only_supported(ast) -> bool:
    from .parser import Call, walk
    return all(n.fname in SUPPORTED for n in walk(ast) if isinstance(n, Call))
