"""Generate the gradebook sample sheet in two formats from one definition.

  examples/gradebook.txt   - Tabula script (batch mode for tabula.cli)
  examples/gradebook.xlsx  - the same sheet as a real Excel workbook

Keeping both from one source means the two can never drift, so the Excel file
is a trustworthy oracle: open it, and every value must match Tabula's output.

Since Revision 2 the formula language is Excel-compatible, so both files use
exactly the same formula text.  Run:  python3 tools/make_gradebook.py
"""
from pathlib import Path

HEADERS = ["Student", "Quiz 1", "Quiz 2", "Assignment", "Exam",
           "Total", "Grade", "Weighted %"]

STUDENTS = [                      # name, quiz1/20, quiz2/20, assignment/20, exam/40
    ("Aditi",   18, 16, 19, 36),
    ("Rohan",   12, 14, 15, 28),
    ("Meera",   20, 19, 20, 38),
    ("Karthik",  9, 11, 13, 22),
    ("Sneha",   15, 17, 16, 31),
]

GRADE = ('=IF(F{r}>=90,"A",IF(F{r}>=80,"B",IF(F{r}>=70,"C","F")))')
WEIGHTED = "=ROUND(B{r}/20*15+C{r}/20*15+D{r}/20*20+E{r}/40*50,1)"

SUMMARY = [                       # label cell (A), formula cell (B)
    ("Class average", "=ROUND(AVERAGE(F2:F6),2)"),
    ("Highest total", "=MAX(F2:F6)"),
    ("Lowest total",  "=MIN(F2:F6)"),
    ("Students",      "=COUNT(F2:F6)"),
    ("Spread",        "=MAX(F2:F6)-MIN(F2:F6)"),
    ("Above average", '=IF(F2>=AVERAGE(F2:F6),"yes","no")'),
    ("Report line",   '="Class average "&ROUND(AVERAGE(F2:F6),1)&" of 100"'),
]

SUMMARY_START = 9                 # summary block begins at row 9


def build_cells() -> list[tuple[str, str]]:
    """Return [(cell_ref, raw_content)] in Tabula dialect, in sheet order."""
    cells: list[tuple[str, str]] = []
    for col, head in zip("ABCDEFGH", HEADERS):
        cells.append((f"{col}1", head))
    for i, (name, q1, q2, asg, exam) in enumerate(STUDENTS):
        r = i + 2
        cells += [(f"A{r}", name), (f"B{r}", str(q1)), (f"C{r}", str(q2)),
                  (f"D{r}", str(asg)), (f"E{r}", str(exam)),
                  (f"F{r}", f"=SUM(B{r}:E{r})"),
                  (f"G{r}", GRADE.format(r=r)),
                  (f"H{r}", WEIGHTED.format(r=r))]
    for j, (label, formula) in enumerate(SUMMARY):
        r = SUMMARY_START + j
        cells += [(f"A{r}", label), (f"B{r}", formula)]
    return cells


def write_script(cells, path: Path) -> None:
    lines = ["# Tabula gradebook sample - generated by tools/make_gradebook.py",
             "# Run:  python3 -m tabula repl examples/gradebook.txt", ""]
    for ref, raw in cells:
        lines.append(f"set {ref} {raw}")
    lines += ["", "show"]
    path.write_text("\n".join(lines) + "\n")


def write_workbook(cells, path: Path) -> None:
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Font, PatternFill

    wb = Workbook()
    ws = wb.active
    ws.title = "Gradebook"
    for ref, raw in cells:
        ws[ref] = raw if raw.startswith("=") else _typed(raw)

    head = Font(bold=True)
    fill = PatternFill("solid", fgColor="EEECE4")
    for col in "ABCDEFGH":
        ws[f"{col}1"].font = head
        ws[f"{col}1"].fill = fill
        ws.column_dimensions[col].width = 13
        ws[f"{col}1"].alignment = Alignment(horizontal="center")
    for j in range(len(SUMMARY)):
        ws[f"A{SUMMARY_START + j}"].font = head
    wb.save(path)


def _typed(raw: str):
    """Numbers stored as numbers so Excel treats them arithmetically."""
    try:
        return int(raw)
    except ValueError:
        return raw


if __name__ == "__main__":
    root = Path(__file__).resolve().parent.parent
    cells = build_cells()
    write_script(cells, root / "examples" / "gradebook.txt")
    write_workbook(cells, root / "examples" / "gradebook.xlsx")
    formulas = sum(1 for _, raw in cells if raw.startswith("="))
    print(f"wrote examples/gradebook.txt and examples/gradebook.xlsx "
          f"({len(cells)} cells, {formulas} formulas)")
